# -*- coding: utf-8 -*-
"""practical-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TQNTPnrO6AEeWk5G_XDkmInrBB8siDb

# 3. Create, initialize and display simple variables and simple strings and use simple formatting for variable.
"""

# creation & iniatilisation
a=4
b="Four"

print("Integer variable is %d"%a)
print("String variable is %s"%b)

