# -*- coding: utf-8 -*-
"""practical-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KaamMVREq20YI_m4iLcKCa68gUEhA4Iq
"""

a=5
b=10

# Addition
a+b

# Multiplication
a*b

# Division
a/b

# Exponentiation
a**b
