# -*- coding: utf-8 -*-
"""Q7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rPfkz5Hjx13qYnQ8bianE40em0yWSSht
"""

import numpy as np


matrix = np.array([[1, -2, 3], [4, -5, 6], [7, 8, -9]])


abs_matrix = np.abs(matrix)
print("Absolute values of matrix:\n", abs_matrix)


neg_matrix = -matrix
print("Negative of matrix:\n", neg_matrix)


new_row = np.array([10, 11, 12])
matrix = np.vstack([matrix, new_row])
print("Matrix with new row:\n", matrix)


matrix = np.delete(matrix, 0, axis=1)
print("Matrix with column removed:\n", matrix)


max_val = np.max(matrix, axis=0)
print("Maximum value in row matrix:", max_val)

max_val = np.max(matrix, axis=1)
print("Maximum value in column matrix:", max_val)


min_val = np.min(matrix[1,:])
print("Minimum value in second row:", min_val)


sum_val = np.sum(matrix)
print("Sum of all elements in matrix:", sum_val)

