# -*- coding: utf-8 -*-
"""practical-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TQNTPnrO6AEeWk5G_XDkmInrBB8siDb

# 2. Perform elementary logical operations in Octave/MATLAB/R (like OR, AND, Checking for Equality, NOT, XOR).
"""

# iniatilisation
a=4
b=6

# OR
a|b

# AND
a&b

# Equatilty
a==b

# Unequality
a!=b

# NOT
~a

# NOT
~b

# XOR
a^b