# # -*- coding: utf-8 -*-
# """Q6

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1lvWzLgfWxkg584NNggritP9QjYHAEr4e
# """

# import numpy as np
# arr = np.array([[1.,2.,3.],[4.,5.,6.]]);
# arr

# arr-arr

# arr*arr

# arr+arr

# arr[0][:]

# arr[:,0]

import numpy as np

def main():
    
    matrix1 = np.array([[1.,2.,3.],[4.,5.,6.]]);
    matrix2 = np.array([[3.,4.,5.],[7.,8.,9.]]);
    
    while True:
        print("1. Add two matrices")
        print("2. Subtract two matrices")
        print("3. Multiply two matrices")
        print("4. Display specific row of a matrix")
        print("5. Display specific column of a matrix")
        print("6. Exit")
        choice = int(input("Enter your choice: "))

        if choice == 1:
            
            print("The addition of two matrices is: ")
            print(np.add(matrix1, matrix2))

        elif choice == 2:
            print("The subtraction of two matrices is: ")
            print(np.subtract(matrix1, matrix2))

        elif choice == 3:
            print("The multiplication of two matrices is: ")
            print(np.multiply(matrix1, matrix2))

        elif choice == 4:
            row = int(input("Enter the row number to display: "))
            print("The specific row of matrix is: ")
            print(matrix1[row-1])

        elif choice == 5:
            col = int(input("Enter the column number to display: "))
            print("The specific column of matrix is: ")
            print(matrix1[:,col-1])

        elif choice == 6:
            break

if __name__ == "__main__":
    main()
