# -*- coding: utf-8 -*-
"""practical-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11TQNTPnrO6AEeWk5G_XDkmInrBB8siDb

# 4. Create/Define single dimension / multi-dimension arrays, and arrays with specific values like array of all ones, all zeros, array with random values within a range, or a diagonal matrix
"""

import numpy as np

a=np.array([1,2,3])
b=np.array([[2,4,6],[8,10,12]])
c=np.zeros(5)
d=np.ones(5)
e=np.random.randint(2,10)
f=np.diag([1,2,3])

a

b

c

d

e

f

