# -*- coding: utf-8 -*-
"""Q5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PgHpOdTWeOy4OGeutje_hgYVGlwHxuEv
"""

import numpy as np
import pandas as pd

arr=np.array([[1,2,3,4],
               [4,5,6,5],
              [7,8,9,6]])
arr

arr.size

arr.shape

len(arr)

len(arr[:,1])

len(arr[1,:])

txt=np.loadtxt("Untitled.txt", dtype='str')

txt

print('Array:\n', arr)
file = open("file1.txt", "w+")
 
content = str(arr)
file.write(content)
file.close()

